/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yp_www_JavaNative */

#ifndef _Included_com_yp_www_JavaNative
#define _Included_com_yp_www_JavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yp_www_JavaNative
 * Method:    testStringArrays
 * Signature: ([Ljava/lang/String;)[Lcom/yp/www/Person;
 */
JNIEXPORT jobjectArray JNICALL Java_com_yp_www_JavaNative_testStringArrays
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
