/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yp_www_JniNativeTest */

#ifndef _Included_com_yp_www_JniNativeTest
#define _Included_com_yp_www_JniNativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_yp_www_JniNativeTest_testInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yp_www_JniNativeTest_testBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_yp_www_JniNativeTest_testShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testByte
 * Signature: (Ljava/lang/Byte;)Ljava/lang/Byte;
 */
JNIEXPORT jobject JNICALL Java_com_yp_www_JniNativeTest_testByte
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testlong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_yp_www_JniNativeTest_testlong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_yp_www_JniNativeTest_testFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_yp_www_JniNativeTest_testDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_yp_www_JniNativeTest
 * Method:    testString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yp_www_JniNativeTest_testString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
